# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI
on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'
      - name: Install dependencies and build 🔧
        run: npm install && npm run compile
        
      - name: Apply version NPM 📦
        run: |
          mv ./dist/package.json ./dist/copy_package.json
          envsubst < ./dist/copy_package.json > ./dist/package.json
        env:
          VERSION: ${{ github.ref_name }}

      - name: Publish package on NPM 📦
        run: cd ./dist && npm publish --access=public
        env:
          TAG: ${{ github.ref_name }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
